### ISSUE TITLE
Excessive error messages with type of number

### ISSUE THREAD

**Issue by plushkinaaa** [viraxslot/online-school-app#37] opened 2022-06-23 21:03 UTC
**Steps to reproduce**
Log-in as Admin
Send POST query to
[http://qa-school-test.quantori.academy/api/v1/categories](https://github.com/viraxslot/online-school-app/issues/url)
with body 
```
{
    "title": 1234
}
```

**Actual behavior**
```
{
    "errors": [
        {
            "value": 1234,
            "msg": "Parameter should be a string",
            "param": "title",
            "location": "body"
        },
        {
            "value": 1234,
            "msg": "Only RU/EN alphabet, space and digits allowed, please change your request",
            "param": "title",
            "location": "body"
        },
        {
            "value": 1234,
            "msg": "You are not allowed to use spaces only",
            "param": "title",
            "location": "body"
        }
    ]
}
```

**Expected behavior**
```
{
    "errors": [
        {
            "value": 1234,
            "msg": "Parameter should be a string",
            "param": "title",
            "location": "body"
        }
    ]
}
```

**Screenshots**
![bug2](https://user-images.githubusercontent.com/106329316/175399110-83c90a05-7ffd-4b47-99de-fa6f3eb0769b.png)

**Comment by viraxslot** [comment] 2022-06-23 21:08
The same question as here: https://github.com/viraxslot/online-school-app/issues/36
Any pros to show only 1 error message?

**Comment by plushkinaaa** [comment] 2022-06-23 21:12
Because the error is in incorrect type of parameter, not in incorrect characters. So why in case of only spaces it's only one error message "You are not allowed to use spaces only"? According to your logic it also should be the error "Only RU/EN alphabet, space and digits allowed, please change your request" too.

**Comment by viraxslot** [comment] 2022-06-23 21:30
Agree. This bug is about the same so closing as a duplicate of https://github.com/viraxslot/online-school-app/issues/36
Will show validation rules 1 by 1.

**Closed by viraxslot** 2022-06-23 21:30 UTC
Labels: question
