### ISSUE TITLE
Incomplete response message (unban user request)

### ISSUE THREAD

**Issue by mariarubina** [viraxslot/online-school-app#62] opened 2022-06-30 08:39 UTC
**Steps to reproduce**
1. Post - login as admin.
2. Post - create a teacher
3. Get - list of teachers
4. Ban a user (teacher) by id 
5. Unban a user by id 

**Actual behavior**

There is no info about the reason and who unbanned 

POST {{host}}/api/v1/change-user-ban?userId=88&ban=false
body
{
  "reason": "just a wish"
}

response body

{
    "result": "User successfully unbanned",
    "isBanned": false,
    "userId": 88,
    "reason": "empty",
    "createdBy": ""
}

**Expected behavior**
"reason" string should be filled like in the request body and "created by" string should be filled with admin name 

**Screenshots**
<img width="857" alt="image" src="https://user-images.githubusercontent.com/105916642/176632749-16ffe1db-0472-458e-b8cb-1dc6b57a9fb4.png">

**Comment by viraxslot** [comment] 2022-07-15 00:06
Duplicate of https://github.com/viraxslot/online-school-app/issues/53

**Closed by viraxslot** 2022-07-15 00:06 UTC
