### ISSUE TITLE
Title with 'space' only

### ISSUE THREAD

**Issue by LiliaUsol** [viraxslot/online-school-app#16] opened 2022-06-20 18:17 UTC
**Steps to reproduce**
Working in postman execute comands below using admin user credentials.

POST http://qa-school-test.quantori.academy/api/v1/categories

{
  "title": "   "
}

**Actual behavior**
Code 200 : New category is created

**Expected behavior**
Code 400: Error message like: ‘Using only space forbidden’ and the list of valuable parameters.
**Screenshots**
![spacestitle](https://user-images.githubusercontent.com/106025715/174658483-4a0da192-3fde-44b9-9c25-c5cc022a15b5.JPG)

**Comment by viraxslot** [comment] 2022-06-21 10:25
Closing as duplicate of https://github.com/viraxslot/online-school-app/issues/17

**Closed** 2022-06-21 10:25 UTC
