### ISSUE TITLE
Created a course material with Armenian language

### ISSUE THREAD

**Issue by BeatBioInfo** [viraxslot/online-school-app#73] opened 2022-07-01 16:31 UTC
**Steps to reproduce**
Create a collection on Postman
Click on the “add request” button
Use the POST method to call a request http://qa-school-test-api.quantori.academy/api/v1/session
Enter the following “string” in the “Body” in the following order
• {
“username”: “admin”,
“password”: “1234”
}
Press the “send” button to generate an “accessToken”.
Click “Add request” to call a 'non-existing material id' in a course
Use the POST method to call a request {{Host}}api/v1/courses/3093/materials/200
Enter the body
{
  "title": "Բարեւ, ինչպես ես",
  "data": "Բարեւ, ինչպես ես",
  "order": 8
}
Then send the request.

**Actual behavior**
• Status code: 200; Ok
Body Response:
{
    "id": 852,
    "title": "Բարեւ, ինչպես ես",
    "data": "Բարեւ, ինչպես ես",
    "order": 8,
    "courseId": 3093
}

**Expected behavior**
• Status code: 400 Bad request
Body Response: "Only RU/EN alphabet, space and digits allowed, please change your request"
![image](https://user-images.githubusercontent.com/80711251/176934602-04166bc8-246f-475d-a34d-3e65bcc63db9.png)

**Screenshots**

**Comment by viraxslot** [comment] 2022-07-15 00:33
Duplicate of https://github.com/viraxslot/online-school-app/issues/72

**Closed by viraxslot** 2022-07-15 00:33 UTC
