### ISSUE TITLE
Admin tries to add new material with not unique title in his course - Unexpected Behaviour

### ISSUE THREAD

**Issue by Tatyana-Kravchenko** [viraxslot/online-school-app#64] opened 2022-07-01 10:27 UTC
**Steps to reproduce**
Admin added new material in his course (courseId: {{courseIdForMaterialsAdmin}}, title: Additional material {{materialPostfix}}, data: "New test desidn techniques", order: 3;) POST {{host}}/api/v1/courses/{{courseIdForMaterialsAdmin}}/materials
Admin saved in environment title of material as {{NotUniqueTitle}}

Admin tries to add new material with title which are existed
Post {{host}}/api/v1/courses/{{courseIdForMaterialsAdmin}}/materials
Body request:
```javascript
{
"title": "{{NotUniqueTitle}}",
"data": "New test desidn techniques",
"order": 3
}
```
Tests:
```javascript
pm.test("Status code is 403", function () {
pm.response.to.have.status(403);
});

pm.test("Response time is less than 1000ms", function () {
pm.expect(pm.response.responseTime).to.be.below(1000);
});

pm.test("Check the text error of is correct", function () {
const jsonData = pm.response.json();
pm.expect(jsonData.error).equal("Title of material should be unique")
});
```

**Actual behaviour**
1. Status code is 200
2. Response time is less than 1000 ms
3. New material with not unique title was added

**Expected behaviour**
Status code is 403
1. Response time is less than 1000 ms
2. New material with not unique title wasn't added
3. Error message (Title of material should be unique) is correct

Screenshots
<img width="957" alt="Bug2HW16" src="https://user-images.githubusercontent.com/105992192/176877205-4d6687cc-75b2-4672-b50b-34be6997d859.png">

**Comment by viraxslot** [comment] 2022-07-15 00:15
Duplicate of https://github.com/viraxslot/online-school-app/issues/63
Please add information that you're expected this behavior for both roles.

**Closed by viraxslot** 2022-07-15 00:15 UTC
