### ISSUE TITLE
Create category: wrong error message when title of invalid special characters

### ISSUE THREAD

**Issue by yanaaleeva** [viraxslot/online-school-app#14] opened 2022-06-19 21:03 UTC
**Steps to reproduce**

1. In Postman create collection, e.g. "Bug report"
2.  Click "Add request"
3. Name request, e.g. "admin login"
4.  Type in Body: 
{
    "username": "admin",
    "password": "************"
}
5. Create admin Token by typing in Tests: const body = pm.response.json()
 pm.environment.set('adminToken', body.accessToken)
6. Send POST request to http://qa-school-test.quantori.academy/api/v1/session
7. Click "Add request" 
8. Name request, e.g. "invalid special characters"
9. Type into Body :
{
  "title": ",.;:*@'"
}
10. Insert Bearer Token "adminToken" into Auth
11. Insert to Tests:
 pm.test("Error text is correct", function () {
    const body = pm.response.json()
       pm.expect(body.errors[0].msg).to.equal("Only RU/EN alphabet, space and digits allowed, please change your request");
});

13. Send Post request to http://qa-school-test.quantori.academy/api/v1/categories

**Actual behavior**
Error message text states: "errors": "Only RU/EN alphabet and digits allowed, please change your request"
**Expected behavior**
Error message text should state:"errors": "Only RU/EN alphabet, space and digits allowed, please change your request"
**Screenshots**
![inv special char_error message](https://user-images.githubusercontent.com/105941331/174500238-fd05e2f5-79fd-4bdd-8dca-26c14662343a.jpg)

**Comment by viraxslot** [comment] 2022-06-23 07:16
Duplicate of https://github.com/viraxslot/online-school-app/issues/13

**Closed by viraxslot** 2022-06-23 07:16 UTC
